server:
  port: 8001
mybatis:
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://192.168.172.129:8761/eureka/
  instance:
    instance-id: user-service
    prefer-ip-address: true
info:
  app.name: microservice
  company.name: www.ldw.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
