server:
  port: 8001
mybatis:
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml
spring:
  application:
    name: microservice-uc
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/airlines?serverTimezone=Asia/Shanghai
    username: root
    password: aaaaa888
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.172.129:8848
        namespace: dev  # 或者具体的 namespace ID
        prefer-ip-address: true  # 让 Nacos 注册服务时使用 IP
          #实例的请求ip
        ip: 192.168.172.129

# 日志配置文件
logging:
  config: classpath:logback-spring.xml