server:
  port: 8001
mybatis:
  type-aliases-package: com.ldw.microservice.entity
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
spring:
  application:
    name: microservice-uc
  datasource:
    dynamic:
      primary: db1         # 默认数据源
      strict: false        # 严格匹配（true 时必须指定，否则报错）
      datasource:
        db1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/airlines?serverTimezone=Asia/Shanghai
          username: root
          password: aaaaa888
        db2:
          url: jdbc:mysql://localhost:3306/luckypai?useSSL=false&serverTimezone=UTC
          username: root
          password: aaaaa888
          driver-class-name: com.mysql.cj.jdbc.Driver



  cloud:
    nacos:
      discovery:
        server-addr: 192.168.172.129:8848
        namespace: dev  # 或者具体的 namespace ID
        prefer-ip-address: true  # 让 Nacos 注册服务时使用 IP
          #实例的请求ip
        ip: 192.168.172.129

# 日志配置文件
logging:
  config: classpath:logback-spring.xml