server:
  port: 8001
spring:
  application:
    name: microservice-uc
  cloud:
    nacos:
      discovery:
        server-addr: 8.138.207.57:8848
        namespace: ""  # 或者具体的 namespace ID
        prefer-ip-address: true  # 让 Nacos 注册服务时使用 IP
          #实例的请求ip
        ip: 192.168.172.129
    config:
      enabled: true
      server-addr: 8.138.207.57:8848
      namespace: ""  # 或者具体的 namespace ID
      file-extension: yml

# 日志配置文件
logging:
  config: classpath:logback-spring.xml